import {
    Button,
    VerticalBox,
    HorizontalBox,
    ScrollView,
    ComboBox,
} from "std-widgets.slint";

import { Position, Tile, GameState } from "types.slint";

export component MainWindow inherits Window {
    // Custom Properties
    in property <int> mine_value;
    in property <[[Tile]]> grid;
    in property <GameState> state: Initial;
    in property <length> text-font-size: self.default-font-size;
    in property <[string]> levels;
    property <bool> m_initial_level_set:false;
    in-out property <int> flags;

    // callbacks
    callback first_move_occured(Position);
    callback expand_selection(Position);
    callback change_flag(Position, bool);
    callback change_visibility(Position, bool);
    callback check_win();
    callback restart();
    callback close();
    callback about();
    callback level_changed(int);

    // public functions
    // For Setting Initial Value of ComboBox
    public function initial_level(level: int) {
        levels_combo.current-value = levels[level];
        if !m_initial_level_set {
            m_initial_level_set = true;
        } else {
            debug("Initial Value for ComboBox Must set only once");
        }
    }

    public function reset_timer() {
        timer.time_elapsed = 0;
    }

    // Setting img to tile
    pure function tile_to_img(tile: Tile) -> image {
        if tile.flagged {
            return @image-url("resources/icons/flag.svg");
        } else if tile.visible {
            if tile.value == mine_value {
                return @image-url("resources/icons/warning.svg");
            } else if tile.value == 0 {
                return @image-url("resources/icons/blank.svg");
            } else if tile.value == 1 {
                return @image-url("resources/icons/1.svg");
            } else if tile.value == 2 {
                return @image-url("resources/icons/2.svg");
            } else if tile.value == 3 {
                return @image-url("resources/icons/3.svg");
            } else if tile.value == 4 {
                return @image-url("resources/icons/4.svg");
            } else if tile.value == 5 {
                return @image-url("resources/icons/5.svg");
            } else if tile.value == 6 {
                return @image-url("resources/icons/6.svg");
            } else if tile.value == 7 {
                return @image-url("resources/icons/7.svg");
            } else if tile.value == 8 {
                return @image-url("resources/icons/8.svg");
            } else {
                return @image-url("resources/icons/empty.svg");
            }
        } else {
            return @image-url("resources/icons/empty.svg");
        }
    }

    title: "MineSweeper";
    icon: @image-url("resources/icons/icon.svg");
    preferred-width: 1280px;
    preferred-height: 720px;

    VerticalBox {
        scroll := ScrollView {
            enabled: root.state == GameState.Initial || root.state == GameState.Normal;
            VerticalLayout {
                alignment: center;
                for row[i] in grid: HorizontalLayout {
                    alignment: center;
                    for button[j] in row: Rectangle {
                        height: btn_img.height;
                        width: btn_img.width;
                        btn_img := Image {
                            source: tile_to_img(button);
                            width: 40px;
                            height: 40px;
                        }

                        touch := TouchArea {
                            enabled: scroll.enabled && !(button.visible && button.value == 0);
                            pointer-event(event) => {
                                if event.button == PointerEventButton.right && event.kind == PointerEventKind.up {
                                    if !button.visible && !button.flagged {
                                        button.flagged = true;
                                        root.flags -= 1;
                                        change_flag(button.position,button.flagged);
                                    } else if !button.visible && button.flagged {
                                        button.flagged = false;
                                        root.flags += 1;
                                        change_flag(button.position,button.flagged);
                                    }
                                    check_win()
                                } else if event.button == PointerEventButton.left && event.kind == PointerEventKind.up {
                                    if button.flagged {
                                        button.flagged = false;
                                        root.flags += 1;
                                        change_flag(button.position,button.flagged);
                                    } else {
                                        if root.state == GameState.Initial {
                                            first_move_occured(button.position);
                                        }
                                        button.visible = true;
                                        change_visibility(button.position, true);
                                        expand_selection(button.position);
                                    }
                                    check_win()
                                }
                            }
                        }
                    }
                }
            }
        }

        HorizontalBox {
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 10px;
            padding-right: 10px;
            spacing: 10px;
            timer := Timer {
                property <duration> time_elapsed;
                interval: 1s;
                running: root.state == GameState.Normal ? true : false;
                triggered() => {
                    time_elapsed += 1s;
                }
            }

            timer_text := Text {
                font-size: text-font-size;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "Time: \{timer.time_elapsed / 1s} sec";
            }

            Text {
                font-size: text-font-size;
                horizontal-alignment: left;
                vertical-alignment: center;
                text: "Flags: \{root.flags}";
                color: red;
            }

            levels_combo := ComboBox {
                enabled: root.state == GameState.Initial;
                model: levels;
                selected() => {
                    level_changed(self.current-index);
                }
            }

            Button {
                icon: @image-url("resources/icons/reset.svg");
                text: "Restart";
                clicked => {
                    root.restart();
                }
            }

            Button {
                icon: @image-url("resources/icons/info.svg");
                text: "About";
                clicked => {
                    about();
                }
            }

            Button {
                icon: @image-url("resources/icons/exit.svg");
                text: "Quit";
                clicked => {
                    root.close();
                }
            }
        }
    }
}
