import {
    Button,
    VerticalBox,
    HorizontalBox,
    ScrollView,
} from "std-widgets.slint";

import { Position, Tile, GameState, GameDifficulty } from "types.slint";

export component MainWindow inherits Window {
    // Custom Properties
    in property <int> mine_value;
    in property <[[Tile]]> grid;
    in property <GameState> state: Initial;
    in property <length> font-size <=> self.default-font-size;
    in-out property <GameDifficulty> difficulty: GameDifficulty.Medium;
    in-out property <int> flags;

    // callbacks
    callback first_move_occured(Position);
    callback expand_selection(Position);
    callback change_flag(Position, bool);
    callback change_visibility(Position, bool);
    callback check_win();
    callback restart();
    callback close();
    callback about();
    callback difficulty_changed();

    // public functions
    public pure function tile_to_img(tile: Tile) -> image {
        if tile.flagged {
            return @image-url("resources/icons/flag.svg");
        } else if tile.visible {
            if tile.value == mine_value {
                return @image-url("resources/icons/warning.svg");
            } else if tile.value == 0 {
                return @image-url("resources/icons/blank.svg");
            } else if tile.value == 1 {
                return @image-url("resources/icons/1.svg");
            } else if tile.value == 2 {
                return @image-url("resources/icons/2.svg");
            } else if tile.value == 3 {
                return @image-url("resources/icons/3.svg");
            } else if tile.value == 4 {
                return @image-url("resources/icons/4.svg");
            } else if tile.value == 5 {
                return @image-url("resources/icons/5.svg");
            } else if tile.value == 6 {
                return @image-url("resources/icons/6.svg");
            } else if tile.value == 7 {
                return @image-url("resources/icons/7.svg");
            } else if tile.value == 8 {
                return @image-url("resources/icons/8.svg");
            } else {
                return @image-url("resources/icons/empty.svg");
            }
        } else {
            return @image-url("resources/icons/empty.svg");
        }
    }

    title: "MineSweeper";
    icon: @image-url("resources/icons/minesweeper.svg");
    preferred-width: 1280px;
    preferred-height: 720px;

    VerticalBox {
        scroll := ScrollView {
            enabled: root.state == GameState.Initial || root.state == GameState.Normal;
            VerticalLayout {
                alignment: center;
                for row[i] in grid: HorizontalLayout {
                    alignment: center;
                    for button[j] in row: Rectangle {
                        height: btn_img.height;
                        width: btn_img.width;
                        btn_img := Image {
                            source: tile_to_img(button);
                            width: 40px;
                            height: 40px;
                        }

                        touch := TouchArea {
                            enabled: scroll.enabled && !(button.visible && button.value == 0);
                            pointer-event(event) => {
                                if event.button == PointerEventButton.right && event.kind == PointerEventKind.up {
                                    if !button.visible && !button.flagged {
                                        button.flagged = true;
                                        flags -= 1;
                                        change_flag(button.position,button.flagged);
                                    } else if !button.visible && button.flagged {
                                        button.flagged = false;
                                        flags += 1;
                                        change_flag(button.position,button.flagged);
                                    }
                                    check_win()
                                } else if event.button == PointerEventButton.left && event.kind == PointerEventKind.up {
                                    if button.flagged {
                                        button.flagged = false;
                                        flags -= 1;
                                        change_flag(button.position,button.flagged);
                                    } else {
                                        if root.state == GameState.Initial {
                                            first_move_occured(button.position);
                                        }
                                        button.visible = true;
                                        change_visibility(button.position, true);
                                        expand_selection(button.position);
                                    }
                                    check_win()
                                }
                            }
                        }
                    }
                }
            }
        }

        HorizontalBox {
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 10px;
            padding-right: 10px;
            spacing: 10px;
            state_text := Text {
                horizontal-alignment: center;
                vertical-alignment: center;
                text: state == GameState.Lose ? "State: Game Over" : state == GameState.Win ? "State: You Won" : "State: Normal";
            }

            Text {
                horizontal-alignment: left;
                vertical-alignment: center;
                text: root.flags;
                color: red;
            }

            easy_btn := Rectangle {
                border-width: 4px;
                border-radius: 12px;
                border-color: difficulty == GameDifficulty.Easy ? #95959f : Colors.transparent;
                Text {
                    text: "Easy";
                    color: easy_btn_area.enabled ? state_text.color : #95959f;
                }

                easy_btn_area := TouchArea {
                    enabled: root.state == GameState.Initial;
                    clicked => {
                        difficulty = GameDifficulty.Easy;
                        difficulty_changed();
                    }
                }
            }

            med_btn := Rectangle {
                border-width: 4px;
                border-radius: 12px;
                border-color: difficulty == GameDifficulty.Medium ? #95959f : Colors.transparent;
                Text {
                    text: "Medium";
                    color: med_btn_area.enabled ? state_text.color : #95959f;
                }

                med_btn_area := TouchArea {
                    enabled: root.state == GameState.Initial;
                    clicked => {
                        difficulty = GameDifficulty.Medium;
                        difficulty_changed();
                    }
                }
            }

            hard_btn := Rectangle {
                border-width: 4px;
                border-radius: 12px;
                border-color: difficulty == GameDifficulty.Hard ? #95959f : Colors.transparent;
                Text {
                    text: "Hard";
                    color: hard_btn_area.enabled ? state_text.color : #95959f;
                }

                hard_btn_area := TouchArea {
                    enabled: root.state == GameState.Initial;
                    clicked => {
                        difficulty = GameDifficulty.Hard;
                        difficulty_changed();
                    }
                }
            }

            Button {
                icon: @image-url("resources/icons/reset.svg");
                icon-size: 28px;
                text: "Restart";
                clicked => {
                    root.restart();
                }
            }

            Button {
                icon: @image-url("resources/icons/info.svg");
                icon-size: 28px;
                text: "About";
                clicked => {
                    about();
                }
            }

            Button {
                icon: @image-url("resources/icons/exit.svg");
                icon-size: 28px;
                text: "Quit";
                clicked => {
                    root.close();
                }
            }
        }
    }
}
